import type {
  AccessPolicyRule,
  Alert,
  Bucket,
  CatalogImage,
  CatalogPlan,
  Database,
  FunctionEnvVar,
  FunctionLogLine,
  FunctionResource,
  Instance,
  Invoice,
  KubernetesCluster,
  LedgerEntry,
  Operation,
  PaymentMethod,
  Project,
  Site,
  StorageAccessKey,
  TeamMember,
  Volume,
  WebhookDelivery,
  WebhookEndpoint,
} from "./types";

export const organization = {
  name: "Northwind Labs",
  id: "org_8ff21",
  walletBalance: 412.6,
  autoReloadEnabled: true,
  autoReloadThreshold: 100,
  autoReloadAmount: 250,
  monthToDateSpend: 186.42,
  monthlyForecast: 331.75,
  budget: 500,
  paymentProvider: "Paystack",
  emailVerified: true,
  paymentVerified: true,
};

export const currentUser = {
  name: "Saurabh Rapatwar",
  email: "saurabh@northwindlabs.io",
  role: "Owner" as const,
  deviceEnrolled: true,
};

export const sites: Site[] = [
  {
    id: "lag-1",
    name: "Lagos 1",
    location: "Lagos, Nigeria",
    status: "healthy",
    capacityReservePct: 30,
    usedCpuPct: 54,
    usedMemoryPct: 61,
    usedStoragePct: 47,
    acceptingNewWork: true,
  },
  {
    id: "abj-1",
    name: "Abuja 1",
    location: "Abuja, Nigeria",
    status: "healthy",
    capacityReservePct: 30,
    usedCpuPct: 38,
    usedMemoryPct: 44,
    usedStoragePct: 29,
    acceptingNewWork: true,
  },
  {
    id: "ams-1",
    name: "Amsterdam 1",
    location: "Amsterdam, Netherlands",
    status: "admission-paused",
    capacityReservePct: 30,
    usedCpuPct: 69,
    usedMemoryPct: 71,
    usedStoragePct: 66,
    acceptingNewWork: false,
  },
];

export const projects: Project[] = [
  {
    id: "prj_core",
    name: "Core Platform",
    description: "Primary API, workers, and shared PostgreSQL.",
    createdAt: "2026-03-11",
    accent: "lemon",
    resourceCount: 9,
    monthlySpend: 118.4,
  },
  {
    id: "prj_data",
    name: "Data Pipeline",
    description: "Batch ingest, object storage, and scheduled functions.",
    createdAt: "2026-04-02",
    accent: "sky",
    resourceCount: 6,
    monthlySpend: 47.9,
  },
  {
    id: "prj_staging",
    name: "Staging",
    description: "Pre-production mirror for release verification.",
    createdAt: "2026-05-19",
    accent: "violet",
    resourceCount: 4,
    monthlySpend: 20.12,
  },
];

export const instances: Instance[] = [
  {
    id: "gi_9a41",
    name: "api-prod-1",
    projectId: "prj_core",
    siteId: "lag-1",
    image: "Ubuntu 24.04 LTS",
    plan: "Standard 4",
    vcpu: 4,
    memoryGb: 8,
    diskGb: 160,
    privateIp: "10.42.10.11",
    privateHostname: "api-prod-1.core.guild.internal",
    adminUser: "saurabh",
    state: "ready",
    protection: "protected",
    passwordSshEnabled: false,
    hourlyPrice: 0.062,
    monthlyMax: 44.64,
    createdAt: "2026-03-12",
    cpuPct: 41,
    memoryPct: 63,
    diskPct: 38,
    lastBackupAt: "2026-08-07 02:10",
  },
  {
    id: "gi_7c02",
    name: "api-prod-2",
    projectId: "prj_core",
    siteId: "abj-1",
    image: "Ubuntu 24.04 LTS",
    plan: "Standard 4",
    vcpu: 4,
    memoryGb: 8,
    diskGb: 160,
    privateIp: "10.42.10.12",
    privateHostname: "api-prod-2.core.guild.internal",
    adminUser: "saurabh",
    state: "ready",
    protection: "protected",
    passwordSshEnabled: false,
    hourlyPrice: 0.062,
    monthlyMax: 44.64,
    createdAt: "2026-03-12",
    cpuPct: 36,
    memoryPct: 58,
    diskPct: 35,
    lastBackupAt: "2026-08-07 02:12",
  },
  {
    id: "gi_2b88",
    name: "worker-1",
    projectId: "prj_core",
    siteId: "lag-1",
    image: "Debian 12",
    plan: "Standard 2",
    vcpu: 2,
    memoryGb: 4,
    diskGb: 80,
    privateIp: "10.42.10.21",
    privateHostname: "worker-1.core.guild.internal",
    adminUser: "saurabh",
    state: "degraded",
    protection: "standard",
    passwordSshEnabled: true,
    hourlyPrice: 0.031,
    monthlyMax: 22.32,
    createdAt: "2026-04-20",
    cpuPct: 92,
    memoryPct: 88,
    diskPct: 74,
    lastBackupAt: "2026-08-07 02:15",
  },
  {
    id: "gi_5f13",
    name: "ingest-runner",
    projectId: "prj_data",
    siteId: "abj-1",
    image: "Rocky Linux 9",
    plan: "Standard 2",
    vcpu: 2,
    memoryGb: 4,
    diskGb: 120,
    privateIp: "10.42.20.11",
    privateHostname: "ingest-runner.data.guild.internal",
    adminUser: "saurabh",
    state: "ready",
    protection: "standard",
    passwordSshEnabled: false,
    hourlyPrice: 0.031,
    monthlyMax: 22.32,
    createdAt: "2026-04-03",
    cpuPct: 22,
    memoryPct: 41,
    diskPct: 56,
    lastBackupAt: "2026-08-07 02:20",
  },
  {
    id: "gi_1d67",
    name: "staging-app",
    projectId: "prj_staging",
    siteId: "lag-1",
    image: "Ubuntu 24.04 LTS",
    plan: "Standard 2",
    vcpu: 2,
    memoryGb: 4,
    diskGb: 80,
    privateIp: "10.42.30.11",
    privateHostname: "staging-app.staging.guild.internal",
    adminUser: "saurabh",
    state: "provisioning",
    protection: "standard",
    passwordSshEnabled: false,
    hourlyPrice: 0.031,
    monthlyMax: 22.32,
    createdAt: "2026-08-07",
    cpuPct: 0,
    memoryPct: 0,
    diskPct: 0,
    lastBackupAt: null,
  },
  {
    id: "gi_4e29",
    name: "legacy-batch",
    projectId: "prj_data",
    siteId: "lag-1",
    image: "AlmaLinux 9",
    plan: "Standard 1",
    vcpu: 1,
    memoryGb: 2,
    diskGb: 40,
    privateIp: "10.42.20.19",
    privateHostname: "legacy-batch.data.guild.internal",
    adminUser: "saurabh",
    state: "stopped",
    protection: "standard",
    passwordSshEnabled: false,
    hourlyPrice: 0.016,
    monthlyMax: 11.52,
    createdAt: "2026-05-01",
    cpuPct: 0,
    memoryPct: 0,
    diskPct: 61,
    lastBackupAt: "2026-08-06 02:20",
  },
];

export const volumes: Volume[] = [
  {
    id: "vol_a1",
    name: "api-data",
    projectId: "prj_core",
    siteId: "lag-1",
    sizeGb: 200,
    attachedTo: "api-prod-1",
    state: "ready",
    monthlyMax: 20,
  },
  {
    id: "vol_b2",
    name: "worker-scratch",
    projectId: "prj_core",
    siteId: "lag-1",
    sizeGb: 100,
    attachedTo: "worker-1",
    state: "ready",
    monthlyMax: 10,
  },
  {
    id: "vol_c3",
    name: "ingest-staging",
    projectId: "prj_data",
    siteId: "abj-1",
    sizeGb: 500,
    attachedTo: null,
    state: "ready",
    monthlyMax: 50,
  },
];

export const databases: Database[] = [
  {
    id: "db_pg1",
    name: "core-primary",
    projectId: "prj_core",
    siteId: "lag-1",
    engine: "PostgreSQL 16",
    plan: "Managed 4",
    storageGb: 200,
    privateHostname: "core-primary.db.guild.internal",
    state: "ready",
    protection: "protected",
    monthlyMax: 68.4,
    lastBackupAt: "2026-08-07 01:30",
    connections: 42,
    maxConnections: 120,
  },
  {
    id: "db_pg2",
    name: "analytics",
    projectId: "prj_data",
    siteId: "abj-1",
    engine: "PostgreSQL 15",
    plan: "Managed 2",
    storageGb: 100,
    privateHostname: "analytics.db.guild.internal",
    state: "ready",
    protection: "standard",
    monthlyMax: 34.2,
    lastBackupAt: "2026-08-07 01:45",
    connections: 11,
    maxConnections: 60,
  },
];

export const buckets: Bucket[] = [
  {
    id: "bkt_assets",
    name: "northwind-assets",
    projectId: "prj_core",
    siteId: "lag-1",
    usedGb: 84.2,
    objects: 128_442,
    versioning: true,
    visibility: "private",
    monthlyMax: 8.42,
  },
  {
    id: "bkt_raw",
    name: "pipeline-raw",
    projectId: "prj_data",
    siteId: "abj-1",
    usedGb: 612.9,
    objects: 2_204_118,
    versioning: true,
    visibility: "private",
    monthlyMax: 61.29,
  },
  {
    id: "bkt_backups",
    name: "app-exports",
    projectId: "prj_staging",
    siteId: "lag-1",
    usedGb: 12.4,
    objects: 3_902,
    versioning: false,
    visibility: "private",
    monthlyMax: 1.24,
  },
];

export const clusters: KubernetesCluster[] = [
  {
    id: "k8s_core",
    name: "core-shared",
    projectId: "prj_core",
    siteId: "lag-1",
    version: "1.31",
    mode: "shared-managed",
    namespaces: 3,
    workloads: 14,
    state: "ready",
    monthlyMax: 52,
  },
  {
    id: "k8s_stg",
    name: "staging-shared",
    projectId: "prj_staging",
    siteId: "abj-1",
    version: "1.31",
    mode: "shared-managed",
    namespaces: 1,
    workloads: 5,
    state: "ready",
    monthlyMax: 26,
  },
];

export const functions: FunctionResource[] = [
  {
    id: "fn_webhook",
    name: "payments-webhook",
    projectId: "prj_core",
    siteId: "lag-1",
    runtime: "Node.js 20",
    trigger: "HTTP",
    state: "ready",
    invocations24h: 18_442,
    errorRate: 0.2,
    avgDurationMs: 84,
    monthlyMax: 6.1,
  },
  {
    id: "fn_nightly",
    name: "nightly-rollup",
    projectId: "prj_data",
    siteId: "abj-1",
    runtime: "Python 3.12",
    trigger: "Schedule",
    state: "ready",
    invocations24h: 24,
    errorRate: 0,
    avgDurationMs: 4_120,
    monthlyMax: 2.4,
  },
  {
    id: "fn_thumb",
    name: "asset-thumbnailer",
    projectId: "prj_data",
    siteId: "abj-1",
    runtime: "Node.js 20",
    trigger: "Storage event",
    state: "degraded",
    invocations24h: 3_104,
    errorRate: 4.8,
    avgDurationMs: 612,
    monthlyMax: 3.8,
  },
  {
    id: "fn_audit",
    name: "audit-fanout",
    projectId: "prj_core",
    siteId: "lag-1",
    runtime: "Python 3.12",
    trigger: "PostgreSQL event",
    state: "ready",
    invocations24h: 942,
    errorRate: 0,
    avgDurationMs: 121,
    monthlyMax: 1.2,
  },
];

export const storageAccessKeys: StorageAccessKey[] = [
  {
    id: "sak_1",
    label: "ingest-pipeline",
    accessKeyId: "GC8N2K7XQJ4RZP1A",
    createdAt: "2026-04-03",
    lastUsedAt: "2026-08-07 06:10",
  },
  {
    id: "sak_2",
    label: "local dev (Saurabh)",
    accessKeyId: "GC5T9M1WYB3HDC6E",
    createdAt: "2026-05-19",
    lastUsedAt: null,
  },
];

export const functionEnvVars: Record<string, FunctionEnvVar[]> = {
  fn_webhook: [
    { key: "PAYSTACK_WEBHOOK_SECRET", value: "whsec_••••••••••••3f2a", secret: true },
    { key: "LOG_LEVEL", value: "info", secret: false },
  ],
  fn_nightly: [
    { key: "ROLLUP_TARGET_TABLE", value: "analytics.daily_rollup", secret: false },
  ],
  fn_thumb: [
    { key: "MAX_DIMENSION_PX", value: "2048", secret: false },
    { key: "SOURCE_BUCKET", value: "pipeline-raw", secret: false },
  ],
  fn_audit: [
    { key: "AUDIT_STREAM_URL", value: "https://••••••••••••.internal/audit", secret: true },
  ],
};

export const functionLogs: Record<string, FunctionLogLine[]> = {
  fn_webhook: [
    { timestamp: "2026-08-07 09:41:02", level: "info", message: "Received event checkout.session.completed" },
    { timestamp: "2026-08-07 09:41:02", level: "info", message: "Signature verified, processing payload" },
    { timestamp: "2026-08-07 09:41:03", level: "info", message: "Wallet credited: +$250.00 (ref ps_ref_8812f0)" },
    { timestamp: "2026-08-07 09:38:47", level: "warn", message: "Retrying provider verification (attempt 2/3)" },
  ],
  fn_nightly: [
    { timestamp: "2026-08-07 00:00:04", level: "info", message: "Rollup started for 2026-08-06" },
    { timestamp: "2026-08-07 00:00:41", level: "info", message: "Rollup completed — 42,118 rows written" },
  ],
  fn_thumb: [
    { timestamp: "2026-08-07 09:12:10", level: "error", message: "Unsupported input format: image/avif" },
    { timestamp: "2026-08-07 09:10:02", level: "info", message: "Thumbnail generated for asset/8842.jpg" },
    { timestamp: "2026-08-07 09:09:58", level: "error", message: "Timed out fetching source object (5.0s)" },
  ],
  fn_audit: [
    { timestamp: "2026-08-07 09:00:00", level: "info", message: "Audit fanout delivered 12 events" },
  ],
};

export const operations: Operation[] = [
  {
    id: "op_7781",
    kind: "Create instance",
    resourceName: "staging-app",
    projectId: "prj_staging",
    startedAt: "2026-08-07 09:41",
    state: "running",
    stages: [
      { label: "Preflight checks", status: "done" },
      { label: "Capacity reserved", status: "done" },
      { label: "Cloning template", status: "done" },
      { label: "Configuring private access", status: "active" },
      { label: "Testing connection", status: "pending" },
      { label: "Ready", status: "pending" },
    ],
  },
  {
    id: "op_7776",
    kind: "Resize instance",
    resourceName: "worker-1",
    projectId: "prj_core",
    startedAt: "2026-08-07 08:12",
    state: "succeeded",
    stages: [
      { label: "Preflight checks", status: "done" },
      { label: "Capacity reserved", status: "done" },
      { label: "Applying new plan", status: "done" },
      { label: "Verifying", status: "done" },
      { label: "Ready", status: "done" },
    ],
  },
  {
    id: "op_7761",
    kind: "Restore database",
    resourceName: "analytics",
    projectId: "prj_data",
    startedAt: "2026-08-06 22:04",
    state: "failed",
    stages: [
      { label: "Preflight checks", status: "done" },
      { label: "Locating recovery point", status: "done" },
      { label: "Restoring to new target", status: "failed" },
      { label: "Verifying", status: "pending" },
    ],
  },
];

export const alerts: Alert[] = [
  {
    id: "al_1",
    severity: "critical",
    title: "Memory pressure sustained above 85%",
    detail:
      "worker-1 has held above 85% memory for 42 minutes. Consider resizing to Standard 4 or reducing concurrency.",
    resource: "worker-1",
    openedAt: "2026-08-07 09:03",
    acknowledged: false,
  },
  {
    id: "al_2",
    severity: "warning",
    title: "Function error rate above threshold",
    detail:
      "asset-thumbnailer is returning errors on 4.8% of invocations over the last hour.",
    resource: "asset-thumbnailer",
    openedAt: "2026-08-07 07:48",
    acknowledged: false,
  },
  {
    id: "al_3",
    severity: "warning",
    title: "Site admission paused",
    detail:
      "Amsterdam 1 stopped accepting new placement because free capacity approached the 30% reserve.",
    resource: "Amsterdam 1",
    openedAt: "2026-08-06 19:22",
    acknowledged: true,
  },
  {
    id: "al_4",
    severity: "info",
    title: "Restore drill completed",
    detail:
      "Standard tier restore drill for core-primary passed. Measured recovery time: 24 minutes.",
    resource: "core-primary",
    openedAt: "2026-08-05 14:10",
    acknowledged: true,
  },
];

export const ledger: LedgerEntry[] = [
  {
    id: "le_9",
    date: "2026-08-07",
    description: "Compute usage — Core Platform",
    kind: "usage",
    amount: -4.12,
    reference: "usg_20260807_core",
  },
  {
    id: "le_8",
    date: "2026-08-06",
    description: "Compute usage — Core Platform",
    kind: "usage",
    amount: -4.09,
    reference: "usg_20260806_core",
  },
  {
    id: "le_7",
    date: "2026-08-05",
    description: "Wallet top-up — Paystack",
    kind: "top-up",
    amount: 250,
    reference: "ps_ref_8812f0",
  },
  {
    id: "le_6",
    date: "2026-08-04",
    description: "Object storage usage — Data Pipeline",
    kind: "usage",
    amount: -2.03,
    reference: "usg_20260804_data",
  },
  {
    id: "le_5",
    date: "2026-08-02",
    description: "Credit for failed restore operation",
    kind: "adjustment",
    amount: 6.5,
    reference: "adj_op_7761",
  },
];

export const webhookEndpoints: WebhookEndpoint[] = [
  {
    id: "wh_1",
    url: "https://hooks.northwindlabs.io/guildcloud",
    events: ["payment.succeeded", "payment.failed", "wallet.low"],
    status: "active",
    createdAt: "2026-04-11",
  },
];

export const webhookDeliveries: WebhookDelivery[] = [
  {
    id: "whd_1",
    endpointId: "wh_1",
    event: "payment.succeeded",
    status: "delivered",
    attempt: 1,
    statusCode: 200,
    occurredAt: "2026-08-05 09:14",
  },
  {
    id: "whd_2",
    endpointId: "wh_1",
    event: "wallet.low",
    status: "failed",
    attempt: 3,
    statusCode: 503,
    occurredAt: "2026-08-03 22:02",
  },
  {
    id: "whd_3",
    endpointId: "wh_1",
    event: "payment.succeeded",
    status: "delivered",
    attempt: 1,
    statusCode: 200,
    occurredAt: "2026-07-05 09:10",
  },
];

export const paymentMethods: PaymentMethod[] = [
  {
    id: "pm_1",
    provider: "Paystack",
    label: "Card ending 4242",
    detail: "Verified 2026-03-11",
    isDefault: true,
    addedAt: "2026-03-11",
  },
  {
    id: "pm_2",
    provider: "Flutterwave",
    label: "Bank transfer — GTBank",
    detail: "Verified 2026-05-02",
    isDefault: false,
    addedAt: "2026-05-02",
  },
];

export const invoices: Invoice[] = [
  { id: "inv_2026_07", period: "July 2026", amount: 214.6, status: "paid", issuedAt: "2026-08-01" },
  { id: "inv_2026_06", period: "June 2026", amount: 198.2, status: "paid", issuedAt: "2026-07-01" },
  { id: "inv_2026_05", period: "May 2026", amount: 176.4, status: "paid", issuedAt: "2026-06-01" },
];

export const team: TeamMember[] = [
  {
    id: "tm_1",
    name: "Saurabh Rapatwar",
    email: "saurabh@northwindlabs.io",
    role: "Owner",
    deviceEnrolled: true,
    lastActive: "2026-08-07 09:44",
  },
  {
    id: "tm_2",
    name: "Amara Obi",
    email: "amara@northwindlabs.io",
    role: "Admin",
    deviceEnrolled: true,
    lastActive: "2026-08-07 08:20",
  },
  {
    id: "tm_3",
    name: "Dan Whitfield",
    email: "dan@northwindlabs.io",
    role: "Developer",
    deviceEnrolled: true,
    lastActive: "2026-08-06 17:55",
  },
  {
    id: "tm_4",
    name: "Priya Raman",
    email: "priya@northwindlabs.io",
    role: "Billing",
    deviceEnrolled: false,
    lastActive: "2026-08-03 11:02",
  },
];

export const accessPolicyRules: AccessPolicyRule[] = [
  {
    id: "apr_1",
    projectId: "prj_core",
    memberId: "tm_3",
    resourceType: "instance",
    resourceId: "gi_9a41",
    createdAt: "2026-04-20",
  },
  {
    id: "apr_2",
    projectId: "prj_core",
    memberId: "tm_3",
    resourceType: "database",
    resourceId: "db_pg1",
    createdAt: "2026-04-20",
  },
  {
    id: "apr_3",
    projectId: "prj_data",
    memberId: "tm_4",
    resourceType: "bucket",
    resourceId: "bkt_raw",
    createdAt: "2026-05-03",
  },
];

export const plans: CatalogPlan[] = [
  {
    id: "std-1",
    name: "Standard 1",
    vcpu: 1,
    memoryGb: 2,
    diskGb: 40,
    hourlyPrice: 0.016,
    monthlyMax: 11.52,
  },
  {
    id: "std-2",
    name: "Standard 2",
    vcpu: 2,
    memoryGb: 4,
    diskGb: 80,
    hourlyPrice: 0.031,
    monthlyMax: 22.32,
  },
  {
    id: "std-4",
    name: "Standard 4",
    vcpu: 4,
    memoryGb: 8,
    diskGb: 160,
    hourlyPrice: 0.062,
    monthlyMax: 44.64,
  },
  {
    id: "std-8",
    name: "Standard 8",
    vcpu: 8,
    memoryGb: 16,
    diskGb: 320,
    hourlyPrice: 0.124,
    monthlyMax: 89.28,
    note: "Limited stock at Lagos 1",
  },
];

export const images: CatalogImage[] = [
  {
    id: "ubuntu-2404",
    name: "Ubuntu",
    version: "24.04 LTS",
    family: "os",
    recommended: true,
    availableSites: ["lag-1", "abj-1", "ams-1"],
  },
  {
    id: "debian-12",
    name: "Debian",
    version: "12",
    family: "os",
    availableSites: ["lag-1", "abj-1"],
  },
  {
    id: "fedora-41",
    name: "Fedora",
    version: "41",
    family: "os",
    availableSites: ["lag-1"],
  },
  {
    id: "rocky-9",
    name: "Rocky Linux",
    version: "9",
    family: "os",
    availableSites: ["lag-1", "abj-1"],
  },
  {
    id: "alma-9",
    name: "AlmaLinux",
    version: "9",
    family: "os",
    availableSites: ["lag-1", "abj-1"],
  },
  {
    id: "docker",
    name: "Docker",
    version: "on Ubuntu 24.04",
    family: "solution",
    availableSites: ["lag-1", "abj-1"],
  },
  {
    id: "wordpress",
    name: "WordPress",
    version: "on Ubuntu 24.04",
    family: "solution",
    availableSites: ["lag-1"],
  },
];

export const marketplace = [
  {
    id: "docker",
    name: "Docker",
    summary: "Container runtime with Compose, preconfigured and hardened.",
    status: "Available",
    owner: "GuildCloud",
  },
  {
    id: "wordpress",
    name: "WordPress",
    summary: "WordPress with Nginx, PHP-FPM, and automated certificate renewal.",
    status: "Available",
    owner: "GuildCloud",
  },
  {
    id: "n8n",
    name: "n8n",
    summary: "Self-hosted workflow automation on a private hostname.",
    status: "In testing",
    owner: "GuildCloud",
  },
  {
    id: "ollama",
    name: "Ollama",
    summary: "Local model serving for developer workloads.",
    status: "Planned",
    owner: "GuildCloud",
  },
];

export const quotas = [
  { label: "Instances", used: 6, limit: 20 },
  { label: "vCPU", used: 15, limit: 64 },
  { label: "Memory (GB)", used: 30, limit: 128 },
  { label: "Block storage (GB)", used: 800, limit: 2000 },
  { label: "Object storage (GB)", used: 710, limit: 2000 },
  { label: "Databases", used: 2, limit: 8 },
];

export const spendSeries = [
  { day: "Jul 08", amount: 4.9 },
  { day: "Jul 12", amount: 5.4 },
  { day: "Jul 16", amount: 5.1 },
  { day: "Jul 20", amount: 6.2 },
  { day: "Jul 24", amount: 6.0 },
  { day: "Jul 28", amount: 6.8 },
  { day: "Aug 01", amount: 7.1 },
  { day: "Aug 05", amount: 6.4 },
  { day: "Aug 07", amount: 6.9 },
];

export const discoveredWorkloads: import("./types").DiscoveredWorkload[] = [
  {
    id: "dw_1",
    name: "web-01",
    kind: "VM",
    spec: "4 vCPU · 8 GB RAM · Ubuntu 22.04",
    sizeGb: 80,
  },
  {
    id: "dw_2",
    name: "web-02",
    kind: "VM",
    spec: "4 vCPU · 8 GB RAM · Ubuntu 22.04",
    sizeGb: 80,
  },
  {
    id: "dw_3",
    name: "orders-db",
    kind: "Database",
    spec: "PostgreSQL 14 · 2 vCPU · 4 GB RAM",
    sizeGb: 140,
  },
  {
    id: "dw_4",
    name: "app-uploads",
    kind: "Object storage",
    spec: "S3-compatible bucket",
    sizeGb: 320,
  },
];

export const migrationJobs: import("./types").MigrationJob[] = [
  {
    id: "mig_9021",
    name: "AWS production import",
    source: "AWS",
    projectId: "prj_core",
    status: "migrating",
    workloadCount: 4,
    startedAt: "2026-08-06 18:00",
    completedAt: null,
    stages: [
      { label: "Discover workloads", status: "done" },
      { label: "Map to GuildCloud plans", status: "done" },
      { label: "Snapshot source", status: "done" },
      { label: "Transfer data", status: "active" },
      { label: "Verify integrity", status: "pending" },
      { label: "Cutover", status: "pending" },
    ],
  },
  {
    id: "mig_8894",
    name: "DigitalOcean staging import",
    source: "DigitalOcean",
    projectId: "prj_staging",
    status: "completed",
    workloadCount: 2,
    startedAt: "2026-07-22 09:00",
    completedAt: "2026-07-22 11:40",
    stages: [
      { label: "Discover workloads", status: "done" },
      { label: "Map to GuildCloud plans", status: "done" },
      { label: "Snapshot source", status: "done" },
      { label: "Transfer data", status: "done" },
      { label: "Verify integrity", status: "done" },
      { label: "Cutover", status: "done" },
    ],
  },
];

export const tickets: import("./types").SupportTicket[] = [
  {
    id: "tk_4471",
    subject: "worker-1 memory pressure won't clear",
    projectId: "prj_core",
    resource: "worker-1",
    status: "open",
    priority: "high",
    protectionTier: "standard",
    createdAt: "2026-08-07 09:10",
    updatedAt: "2026-08-07 09:52",
    firstResponseTargetMinutes: 120,
    firstResponseAt: "2026-08-07 09:44",
    messages: [
      {
        id: "m1",
        author: "Saurabh Rapatwar",
        role: "customer",
        body: "worker-1 has been above 85% memory for almost an hour and the alert isn't clearing on its own. Can someone check whether this is a leak or if we just need to resize?",
        at: "2026-08-07 09:10",
      },
      {
        id: "m2",
        author: "GuildCloud Support",
        role: "support",
        body: "Looking at it now — memory climbed steadily since 08:20 with no corresponding drop in request volume, which points to a leak rather than load. Safest immediate fix is a resize to Standard 4 to buy headroom while we confirm. Want me to queue that?",
        at: "2026-08-07 09:44",
      },
      {
        id: "m3",
        author: "Saurabh Rapatwar",
        role: "customer",
        body: "Yes please, go ahead with the resize.",
        at: "2026-08-07 09:52",
      },
    ],
  },
  {
    id: "tk_4468",
    subject: "Restore to analytics failed — need it re-run",
    projectId: "prj_data",
    resource: "analytics",
    status: "pending",
    priority: "urgent",
    protectionTier: "standard",
    createdAt: "2026-08-06 22:10",
    updatedAt: "2026-08-07 08:05",
    firstResponseTargetMinutes: 60,
    firstResponseAt: "2026-08-06 22:41",
    messages: [
      {
        id: "m1",
        author: "Saurabh Rapatwar",
        role: "customer",
        body: "The restore operation for analytics (op_7761) failed at the 'Restoring to new target' stage. I need this database back before tomorrow morning.",
        at: "2026-08-06 22:10",
      },
      {
        id: "m2",
        author: "GuildCloud Support",
        role: "support",
        body: "Confirmed — the restore target ran out of provisioned storage mid-copy, not a problem with the backup itself. We're re-running it against a target with headroom now.",
        at: "2026-08-06 22:41",
      },
      {
        id: "m3",
        author: "GuildCloud Support",
        role: "support",
        body: "Re-run is queued behind capacity admission at Abuja 1. Will update as soon as it starts.",
        at: "2026-08-07 08:05",
      },
    ],
  },
  {
    id: "tk_4459",
    subject: "asset-thumbnailer error rate — is this expected?",
    projectId: "prj_data",
    resource: "asset-thumbnailer",
    status: "open",
    priority: "normal",
    protectionTier: "standard",
    createdAt: "2026-08-07 07:50",
    updatedAt: "2026-08-07 07:50",
    firstResponseTargetMinutes: 240,
    firstResponseAt: null,
    messages: [
      {
        id: "m1",
        author: "Saurabh Rapatwar",
        role: "customer",
        body: "Seeing a 4.8% error rate on asset-thumbnailer over the last hour. Nothing changed on our side — can you check if this is platform-side?",
        at: "2026-08-07 07:50",
      },
    ],
  },
  {
    id: "tk_4440",
    subject: "Question about prorated billing on a mid-cycle resize",
    projectId: "prj_core",
    resource: null,
    status: "resolved",
    priority: "low",
    protectionTier: null,
    createdAt: "2026-08-04 14:02",
    updatedAt: "2026-08-04 16:30",
    firstResponseTargetMinutes: 480,
    firstResponseAt: "2026-08-04 14:55",
    messages: [
      {
        id: "m1",
        author: "Saurabh Rapatwar",
        role: "customer",
        body: "If I resize worker-1 mid-month, how is the difference billed — do I get charged the new hourly rate immediately or at the next cycle?",
        at: "2026-08-04 14:02",
      },
      {
        id: "m2",
        author: "GuildCloud Support",
        role: "support",
        body: "Immediately — the hourly rate switches the moment the resize completes, and your ledger shows the old and new rate as separate usage line items so it stays auditable.",
        at: "2026-08-04 14:55",
      },
      {
        id: "m3",
        author: "Saurabh Rapatwar",
        role: "customer",
        body: "Got it, that's exactly what I needed to know. Thanks!",
        at: "2026-08-04 16:30",
      },
    ],
  },
  {
    id: "tk_4402",
    subject: "Requesting higher instance quota for Core Platform",
    projectId: "prj_core",
    resource: null,
    status: "closed",
    priority: "low",
    protectionTier: null,
    createdAt: "2026-07-30 11:15",
    updatedAt: "2026-07-31 09:20",
    firstResponseTargetMinutes: 480,
    firstResponseAt: "2026-07-30 15:40",
    messages: [
      {
        id: "m1",
        author: "Saurabh Rapatwar",
        role: "customer",
        body: "We're at 6/8 instances on Core Platform's old quota and about to launch a new service. Can we raise the instance limit to 20?",
        at: "2026-07-30 11:15",
      },
      {
        id: "m2",
        author: "GuildCloud Support",
        role: "support",
        body: "Approved after a quick capacity and payment-history check — your instance limit is now 20. Let us know if the new service needs more vCPU or memory headroom too.",
        at: "2026-07-31 09:20",
      },
    ],
  },
];

export function projectName(projectId: string) {
  return projects.find((p) => p.id === projectId)?.name ?? "Unknown project";
}

export function siteName(siteId: string) {
  return sites.find((s) => s.id === siteId)?.name ?? "Unknown site";
}

export function money(value: number) {
  return `$${value.toFixed(2)}`;
}

// Pinned locale/timezone (not the server's or browser's default) so
// server-rendered and client-hydrated output always match exactly - a bare
// toLocaleDateString()/toLocaleString() call resolves differently per
// environment (e.g. Node defaults to "8/8/2026", en-GB browsers render
// "08/08/2026" for the same Date), which is a real hydration-mismatch
// source, not just a cosmetic one.
export function formatDate(value: string | Date) {
  return new Date(value).toLocaleDateString("en-US", { timeZone: "UTC" });
}

export function formatDateTime(value: string | Date) {
  return new Date(value).toLocaleString("en-US", { timeZone: "UTC" });
}
