-- Opt-in password SSH per master plan §10 ("password SSH is opt-in,
-- private-route only, never stored by GuildCloud"). The plaintext is
-- generated by the worker at provisioning time (async, so it can't be
-- shown synchronously like the mock storage-keys "reveal once" flow),
-- held transiently in Supabase Vault under a per-instance secret name,
-- and permanently deleted the moment the customer reveals it once - the
-- closest honest implementation of "never stored" for a value that has
-- to survive from an async worker run until the customer next opens the
-- console. See docs/phase-2/data-model.md and threat-model.md finding #7.
alter table instances add column password_ssh_enabled boolean not null default false;

-- Mirrors get_vault_secret's existing pattern (vault isn't exposed via
-- PostgREST directly). Write-side counterpart, used only by the site
-- worker to stash a freshly generated password.
create or replace function public.set_vault_secret(p_secret_name text, p_secret_value text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  perform vault.create_secret(p_secret_value, p_secret_name);
end;
$$;

revoke execute on function public.set_vault_secret(text, text) from public, anon, authenticated;
grant execute on function public.set_vault_secret(text, text) to service_role, site_worker_guild_a;

-- Customer-facing reveal-once. Internal authorization check (same pattern
-- as log_audit_event's Phase 1 hardening fix) means it's safe to grant to
-- every authenticated user, not just this instance's org - the function
-- itself refuses on behalf of anyone who isn't Owner/Admin of the
-- instance's own organization. Deletes the vault secret as part of the
-- same call that reveals it - a second call for the same instance always
-- returns null, not the same password again.
create or replace function public.reveal_instance_ssh_password(p_instance_id uuid)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_org_id uuid;
  v_secret_id uuid;
  v_value text;
begin
  select organization_id into v_org_id from instances where id = p_instance_id;
  if v_org_id is null then
    raise exception 'instance not found';
  end if;
  if not public.has_org_role(v_org_id, array['Owner', 'Admin']) then
    raise exception 'not authorized';
  end if;

  select id, decrypted_secret into v_secret_id, v_value
  from vault.decrypted_secrets
  where name = 'instance_ssh_password_' || p_instance_id::text;

  if v_secret_id is null then
    return null;
  end if;

  perform vault.delete_secret(v_secret_id);
  return v_value;
end;
$$;

revoke execute on function public.reveal_instance_ssh_password(uuid) from public, anon;
grant execute on function public.reveal_instance_ssh_password(uuid) to authenticated;
